/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ktgiuaky_2011062563_2011062086;

import TCP.Cau1.frmCountEvenAndOddTCP;
import TCP.Cau2.frmFindMinTCP;
import TCP.Cau3.frmNameFormatTCP;
import TCP.Cau4.frmMoveArrayTCP;
import UDP.Cau1.frmCountEvenOddUDP;
import UDP.Cau2.frmFindMinUDP;
import UDP.Cau3.frmNameFormatUDP;
import UDP.Cau4.frmMoveArrayUDP;


/**
 *
 * @author WitherDragon
 */
public class frmHome extends javax.swing.JFrame {
    private RunServer runServer;
    
    public frmHome() {
        initComponents();
        runServer=new RunServer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mCau1TCP = new javax.swing.JMenuItem();
        mCau2TCP = new javax.swing.JMenuItem();
        mCau3TCP = new javax.swing.JMenuItem();
        mmCau4TCP = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mCau1UDP = new javax.swing.JMenuItem();
        mCau2UDP = new javax.swing.JMenuItem();
        mCau3UDP = new javax.swing.JMenuItem();
        mCau4UDP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kiem tra giua ky");

        jMenu1.setText("TCP");

        mCau1TCP.setText("Cau1-Dem chan le");
        mCau1TCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCau1TCPActionPerformed(evt);
            }
        });
        jMenu1.add(mCau1TCP);

        mCau2TCP.setText("Cau2-Tim 2 so nho nhat");
        mCau2TCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCau2TCPActionPerformed(evt);
            }
        });
        jMenu1.add(mCau2TCP);

        mCau3TCP.setText("Cau3-Chuan hoa ten");
        mCau3TCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCau3TCPActionPerformed(evt);
            }
        });
        jMenu1.add(mCau3TCP);

        mmCau4TCP.setText("Cau4-Di chuyen mang");
        mmCau4TCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmCau4TCPActionPerformed(evt);
            }
        });
        jMenu1.add(mmCau4TCP);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("UDP");

        mCau1UDP.setText("Cau1-Dem chan le");
        mCau1UDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCau1UDPActionPerformed(evt);
            }
        });
        jMenu2.add(mCau1UDP);

        mCau2UDP.setText("Cau2-Tim 2 so nho nhat");
        mCau2UDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCau2UDPActionPerformed(evt);
            }
        });
        jMenu2.add(mCau2UDP);

        mCau3UDP.setText("Cau3-Chuan hoa ten");
        mCau3UDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCau3UDPActionPerformed(evt);
            }
        });
        jMenu2.add(mCau3UDP);

        mCau4UDP.setText("Cau4-Di chuyen mang");
        mCau4UDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCau4UDPActionPerformed(evt);
            }
        });
        jMenu2.add(mCau4UDP);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mCau1TCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCau1TCPActionPerformed
        runServer.runTcpServer1();
        frmCountEvenAndOddTCP countEvenAndOddTCP =new frmCountEvenAndOddTCP();
        countEvenAndOddTCP.setVisible(true);
    }//GEN-LAST:event_mCau1TCPActionPerformed

    private void mCau2TCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCau2TCPActionPerformed
        runServer.runTcpServer2();
        frmFindMinTCP findMinTCP =new frmFindMinTCP();
        findMinTCP.setVisible(true);
    }//GEN-LAST:event_mCau2TCPActionPerformed

    private void mCau3TCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCau3TCPActionPerformed
        runServer.runTcpServer3();
        frmNameFormatTCP findNameFormatTCP =new frmNameFormatTCP();
        findNameFormatTCP.setVisible(true);
    }//GEN-LAST:event_mCau3TCPActionPerformed

    private void mmCau4TCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmCau4TCPActionPerformed
        runServer.runTcpServer4();
        frmMoveArrayTCP findMoveArrayTCP =new frmMoveArrayTCP();
        findMoveArrayTCP.setVisible(true);
    }//GEN-LAST:event_mmCau4TCPActionPerformed

    private void mCau1UDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCau1UDPActionPerformed
        runServer.runUdpServer1();
        frmCountEvenOddUDP countEvenAndOddUDP  =new frmCountEvenOddUDP();
        countEvenAndOddUDP.setVisible(true);
    }//GEN-LAST:event_mCau1UDPActionPerformed

    private void mCau2UDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCau2UDPActionPerformed
        runServer.runUdpServer2();
        frmFindMinUDP findMinUDP  =new frmFindMinUDP();
        findMinUDP.setVisible(true);
    }//GEN-LAST:event_mCau2UDPActionPerformed

    private void mCau3UDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCau3UDPActionPerformed
        runServer.runUdpServer3();
        frmNameFormatUDP nameFormatUDP  =new frmNameFormatUDP();
        nameFormatUDP.setVisible(true);
    }//GEN-LAST:event_mCau3UDPActionPerformed

    private void mCau4UDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCau4UDPActionPerformed
        runServer.runUdpServer4();
        frmMoveArrayUDP moveArrayUDP  =new frmMoveArrayUDP();
        moveArrayUDP.setVisible(true);
    }//GEN-LAST:event_mCau4UDPActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mCau1TCP;
    private javax.swing.JMenuItem mCau1UDP;
    private javax.swing.JMenuItem mCau2TCP;
    private javax.swing.JMenuItem mCau2UDP;
    private javax.swing.JMenuItem mCau3TCP;
    private javax.swing.JMenuItem mCau3UDP;
    private javax.swing.JMenuItem mCau4UDP;
    private javax.swing.JMenuItem mmCau4TCP;
    // End of variables declaration//GEN-END:variables
}
